from django.urls import path

from .views import (
    AdminPanelDriversListView,
    AdminPanelDriverDetailView,
    AdminPanelRidersListView,
    AdminPanelRiderDetailView,
    AdminPanelSavedCardsListView,
    AdminOrdersListView,
    AdminOrdersDetailView,
    AdminRideTypesListView,
    AdminRideTypesDetailView,
    AdminOrderItemsListView,
    AdminOrderItemsDetailView,
    AdminAdditionalPassengersListView,
    AdminAdditionalPassengersDetailView,
    AdminOrderPreferencesListView,
    AdminOrderPreferencesDetailView,
    AdminUserOrderPreferencesListView,
    AdminUserOrderPreferencesDetailView,
    AdminOrderDriversListView,
    AdminOrderDriversDetailView,
    AdminSurgePricingsListView,
    AdminSurgePricingsDetailView,
    AdminCancelOrdersListView,
    AdminCancelOrdersDetailView,
    AdminOrderPaymentSplitsListView,
    AdminOrderPaymentSplitsDetailView,
    AdminPromoCodesListView,
    AdminPromoCodesDetailView,
    AdminOrderPromoCodesListView,
    AdminOrderPromoCodesDetailView,
    AdminRatingFeedbackTagsListView,
    AdminRatingFeedbackTagsDetailView,
    AdminTripRatingsListView,
    AdminTripRatingsDetailView,
    AdminDriverRiderRatingsListView,
    AdminDriverRiderRatingsDetailView,
    AdminDriverCashoutsListView,
    AdminDriverCashoutsDetailView,
    AdminAnalyticsDashboardView,
    AdminPanelDriverVerificationListView,
    AdminPanelDriverVerificationDetailView,
    AdminPanelUploadTypesListView,
    AdminPanelUploadTypesDetailView,
    AdminPanelLegalTypesListView,
    AdminPanelLegalTypesDetailView,
    AdminPanelRegistrationTypesListView,
    AdminPanelRegistrationTypesDetailView,
    AdminPanelTermsTypesListView,
    AdminPanelTermsTypesDetailView,
)

app_name = 'admin_panel'

urlpatterns = [
    path('drivers/', AdminPanelDriversListView.as_view(), name='drivers-list'),
    path('drivers/<int:driver_id>/', AdminPanelDriverDetailView.as_view(), name='drivers-detail'),
    path('riders/', AdminPanelRidersListView.as_view(), name='riders-list'),
    path('riders/<int:rider_id>/', AdminPanelRiderDetailView.as_view(), name='riders-detail'),
    path('payment/saved-cards/', AdminPanelSavedCardsListView.as_view(), name='admin-saved-cards-list'),

    # Orders domain (Admin Panel frontend)
    path('orders/', AdminOrdersListView.as_view(), name='admin-orders-list'),
    path('orders/<int:order_id>/', AdminOrdersDetailView.as_view(), name='admin-orders-detail'),
    path('ride-types/', AdminRideTypesListView.as_view(), name='admin-ride-types-list'),
    path('ride-types/<int:ride_type_id>/', AdminRideTypesDetailView.as_view(), name='admin-ride-types-detail'),
    path('order-items/', AdminOrderItemsListView.as_view(), name='admin-order-items-list'),
    path('order-items/<int:order_item_id>/', AdminOrderItemsDetailView.as_view(), name='admin-order-items-detail'),
    path('additional-passengers/', AdminAdditionalPassengersListView.as_view(), name='admin-additional-passengers-list'),
    path('additional-passengers/<int:additional_passenger_id>/', AdminAdditionalPassengersDetailView.as_view(), name='admin-additional-passengers-detail'),
    path('order-preferences/', AdminOrderPreferencesListView.as_view(), name='admin-order-preferences-list'),
    path('order-preferences/<int:order_preferences_id>/', AdminOrderPreferencesDetailView.as_view(), name='admin-order-preferences-detail'),
    path('order-preferences-admin/', AdminUserOrderPreferencesListView.as_view(), name='admin-user-order-preferences-list'),
    path('order-preferences-admin/<int:user_order_preferences_id>/', AdminUserOrderPreferencesDetailView.as_view(), name='admin-user-order-preferences-detail'),
    path('order-drivers/', AdminOrderDriversListView.as_view(), name='admin-order-drivers-list'),
    path('order-drivers/<int:order_driver_id>/', AdminOrderDriversDetailView.as_view(), name='admin-order-drivers-detail'),
    path('surge-pricings/', AdminSurgePricingsListView.as_view(), name='admin-surge-pricings-list'),
    path('surge-pricings/<int:surge_pricing_id>/', AdminSurgePricingsDetailView.as_view(), name='admin-surge-pricings-detail'),
    path('cancel-orders/', AdminCancelOrdersListView.as_view(), name='admin-cancel-orders-list'),
    path('cancel-orders/<int:cancel_order_id>/', AdminCancelOrdersDetailView.as_view(), name='admin-cancel-orders-detail'),
    path('order-payment-status/', AdminOrderPaymentSplitsListView.as_view(), name='admin-order-payment-status-list'),
    path('order-payment-status/<int:payment_split_id>/', AdminOrderPaymentSplitsDetailView.as_view(), name='admin-order-payment-status-detail'),
    path('promo-codes/', AdminPromoCodesListView.as_view(), name='admin-promo-codes-list'),
    path('promo-codes/<int:promo_code_id>/', AdminPromoCodesDetailView.as_view(), name='admin-promo-codes-detail'),
    path('order-promo-codes/', AdminOrderPromoCodesListView.as_view(), name='admin-order-promo-codes-list'),
    path('order-promo-codes/<int:order_promo_code_id>/', AdminOrderPromoCodesDetailView.as_view(), name='admin-order-promo-codes-detail'),
    path('rating-feedback/', AdminRatingFeedbackTagsListView.as_view(), name='admin-rating-feedback-list'),
    path('rating-feedback/<int:rating_feedback_tag_id>/', AdminRatingFeedbackTagsDetailView.as_view(), name='admin-rating-feedback-detail'),
    path('trip-ratings/', AdminTripRatingsListView.as_view(), name='admin-trip-ratings-list'),
    path('trip-ratings/<int:trip_rating_id>/', AdminTripRatingsDetailView.as_view(), name='admin-trip-ratings-detail'),
    path('driver-rider-ratings/', AdminDriverRiderRatingsListView.as_view(), name='admin-driver-rider-ratings-list'),
    path('driver-rider-ratings/<int:driver_rider_rating_id>/', AdminDriverRiderRatingsDetailView.as_view(), name='admin-driver-rider-ratings-detail'),
    path('driver-cashouts/', AdminDriverCashoutsListView.as_view(), name='admin-driver-cashouts-list'),
    path('driver-cashouts/<int:driver_cashout_id>/', AdminDriverCashoutsDetailView.as_view(), name='admin-driver-cashouts-detail'),
    path('analytics/dashboard/', AdminAnalyticsDashboardView.as_view(), name='admin-analytics-dashboard'),

    path('verification-drivers/', AdminPanelDriverVerificationListView.as_view(), name='verification-drivers-list'),
    path('verification-drivers/<int:verification_id>/', AdminPanelDriverVerificationDetailView.as_view(), name='verification-drivers-detail'),
    path('upload-driver-identification/', AdminPanelUploadTypesListView.as_view(), name='upload-identification-list'),
    path('upload-driver-identification/<int:upload_type_id>/', AdminPanelUploadTypesDetailView.as_view(), name='upload-identification-detail'),
    path('legal-driver-identification/', AdminPanelLegalTypesListView.as_view(), name='legal-identification-list'),
    path('legal-driver-identification/<int:legal_type_id>/', AdminPanelLegalTypesDetailView.as_view(), name='legal-identification-detail'),
    path('registration-driver-identification/', AdminPanelRegistrationTypesListView.as_view(), name='registration-identification-list'),
    path('registration-driver-identification/<int:registration_type_id>/', AdminPanelRegistrationTypesDetailView.as_view(), name='registration-identification-detail'),
    path('terms-driver-identification/', AdminPanelTermsTypesListView.as_view(), name='terms-identification-list'),
    path('terms-driver-identification/<int:terms_type_id>/', AdminPanelTermsTypesDetailView.as_view(), name='terms-identification-detail'),
]
