# Generated by Django 5.2.6 on 2025-11-12 15:26

from django.db import migrations, models


def clear_verification_codes(apps, schema_editor):
    """
    Clear all existing verification codes before changing field length
    """
    VerificationCode = apps.get_model('accounts', 'VerificationCode')
    VerificationCode.objects.all().delete()


def reverse_clear_verification_codes(apps, schema_editor):
    """
    Reverse migration - nothing to do
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresettoken_verificationcode'),
    ]

    operations = [
        migrations.RunPython(clear_verification_codes, reverse_clear_verification_codes),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=4, verbose_name='Verification Code'),
        ),
    ]
