# Generated by Django 5.2.8 on 2025-11-15 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_verificationcode_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatting_preference', models.CharField(choices=[('no_communication', 'No Communication'), ('casual', 'Casual'), ('friendly', 'Friendly')], default='no_communication', help_text='Preferred communication style during rides', max_length=20, verbose_name='Chatting Preference')),
                ('temperature_preference', models.CharField(choices=[('warm', 'Warm (25°C and above)'), ('comfortable', 'Comfortable (22-24°C)'), ('cool', 'Cool (18-21°C)'), ('cold', 'Cold (below 18°C)')], default='comfortable', help_text='Preferred temperature range in the vehicle', max_length=20, verbose_name='Temperature Preference')),
                ('music_preference', models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('hip_hop', 'Hip Hop'), ('electronic', 'Electronic'), ('country', 'Country'), ('no_music', 'No Music')], default='pop', help_text='Preferred music genre', max_length=20, verbose_name='Music Preference')),
                ('volume_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('mute', 'Mute')], default='medium', help_text='Preferred music volume level', max_length=10, verbose_name='Volume Level')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(help_text='User who owns these preferences', on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
                'ordering': ['-updated_at'],
            },
        ),
    ]
