# Generated by Django 5.2.8 on 2025-11-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userpreferences'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userpreferences',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_preferences'),
        ),
    ]
