# Generated by Django 5.2.6 on 2025-11-21 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_user_email_idx_customuser_user_phone_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationGenerate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(help_text='Unique invitation code for the user', max_length=20, unique=True, verbose_name='Invite Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.OneToOneField(help_text='User who generated the invitation code', on_delete=django.db.models.deletion.CASCADE, related_name='invitation_generate', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Invitation Generate',
                'verbose_name_plural': 'Invitation Generates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='inv_gen_user_idx'), models.Index(fields=['invite_code'], name='inv_gen_code_idx'), models.Index(fields=['created_at'], name='inv_gen_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvitationUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this invitation is still active', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('receiver', models.ForeignKey(blank=True, help_text='User who used the invitation code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Receiver')),
                ('sender', models.ForeignKey(help_text='User who sent the invitation (owner of the invitation code)', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Invitation User',
                'verbose_name_plural': 'Invitation Users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender'], name='inv_user_sender_idx'), models.Index(fields=['receiver'], name='inv_user_receiver_idx'), models.Index(fields=['is_active'], name='inv_user_active_idx'), models.Index(fields=['created_at'], name='inv_user_created_idx'), models.Index(fields=['sender', 'is_active'], name='inv_user_sender_active_idx')],
            },
        ),
    ]
