# Generated by Django 5.2.6 on 2025-11-21 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_invitationgenerate_invitationusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinVerificationForUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(help_text='4-digit PIN code', max_length=4, verbose_name='PIN')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(help_text='User who owns the PIN', on_delete=django.db.models.deletion.CASCADE, related_name='pin_verification', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'PIN Verification For User',
                'verbose_name_plural': 'PIN Verifications For Users',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user'], name='pin_user_idx'), models.Index(fields=['pin'], name='pin_code_idx'), models.Index(fields=['created_at'], name='pin_created_idx'), models.Index(fields=['updated_at'], name='pin_updated_idx')],
            },
        ),
    ]
