# Generated by Django 5.2.6 on 2025-12-07 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_pinverificationforuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tax_number',
            field=models.CharField(blank=True, help_text='Optional. Enter your tax number (GST/HST).', max_length=15, null=True, verbose_name='Tax Number (GST/HST)'),
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Vehicle brand (e.g., Toyota, Honda, etc.)', max_length=100, verbose_name='Brand of car')),
                ('model', models.CharField(help_text='Vehicle model (e.g., Camry, Accord, etc.)', max_length=100, verbose_name='Model of car')),
                ('year_of_manufacture', models.IntegerField(help_text='Year the vehicle was manufactured (2015 or newer)', verbose_name='Year of Manufacture')),
                ('vin', models.CharField(help_text='Unique vehicle identification number', max_length=17, unique=True, verbose_name='Vehicle Identification Number (VIN)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(help_text='Driver who owns this vehicle', on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_details', to=settings.AUTH_USER_MODEL, verbose_name='Driver')),
            ],
            options={
                'verbose_name': 'Vehicle Detail',
                'verbose_name_plural': 'Vehicle Details',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image of the vehicle', upload_to='vehicles/', verbose_name='Vehicle Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('vehicle', models.ForeignKey(help_text='Vehicle these images belong to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.vehicledetails', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Image',
                'verbose_name_plural': 'Vehicle Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type_preference', models.CharField(choices=[('short_trips', 'Short trips (under 5 km)'), ('medium_trips', 'Medium trips (5-15 km)'), ('long_trips', 'Long trips (over 15 km)'), ('any', 'Any trip length')], default='any', help_text='Preferred trip length', max_length=20, verbose_name='Trip Type Preference')),
                ('maximum_pickup_distance', models.CharField(choices=[('1', '1 km'), ('3', '3 km'), ('5', '5 km'), ('10', '10 km'), ('15', '15 km'), ('20', '20 km')], default='5', help_text='Maximum distance driver is willing to travel for pickup', max_length=10, verbose_name='Maximum Pickup Distance')),
                ('preferred_working_hours', models.CharField(choices=[('morning', 'Morning (6 AM - 12 PM)'), ('afternoon', 'Afternoon (12 PM - 6 PM)'), ('evening', 'Evening (6 PM - 12 AM)'), ('night', 'Night (12 AM - 6 AM)'), ('any', 'Any time')], default='any', help_text='Preferred time of day to work', max_length=20, verbose_name='Preferred Working Hours')),
                ('notification_intensity', models.CharField(choices=[('minimal', 'Minimal (only ride requests)'), ('moderate', 'Moderate (ride requests + updates)'), ('high', 'High (all notifications)')], default='minimal', help_text='How many notifications to receive', max_length=20, verbose_name='Notification Intensity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(help_text='Driver who owns these preferences', on_delete=django.db.models.deletion.CASCADE, related_name='driver_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Driver Preference',
                'verbose_name_plural': 'Driver Preferences',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user'], name='driver_pref_user_idx'), models.Index(fields=['updated_at'], name='driver_pref_updated_idx'), models.Index(fields=['user', 'updated_at'], name='driver_pref_user_updated_idx'), models.Index(fields=['trip_type_preference'], name='driver_pref_trip_type_idx'), models.Index(fields=['preferred_working_hours'], name='driver_pref_working_hours_idx')],
                'constraints': [models.UniqueConstraint(fields=('user',), name='unique_driver_preferences')],
            },
        ),
        migrations.AddIndex(
            model_name='vehicledetails',
            index=models.Index(fields=['user'], name='vehicle_user_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledetails',
            index=models.Index(fields=['vin'], name='vehicle_vin_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledetails',
            index=models.Index(fields=['brand'], name='vehicle_brand_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledetails',
            index=models.Index(fields=['model'], name='vehicle_model_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledetails',
            index=models.Index(fields=['year_of_manufacture'], name='vehicle_year_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledetails',
            index=models.Index(fields=['updated_at'], name='vehicle_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledetails',
            index=models.Index(fields=['user', 'updated_at'], name='vehicle_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleimages',
            index=models.Index(fields=['vehicle'], name='veh_img_vehicle_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleimages',
            index=models.Index(fields=['created_at'], name='veh_img_created_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleimages',
            index=models.Index(fields=['vehicle', 'created_at'], name='veh_img_veh_created_idx'),
        ),
    ]
