# Generated by Django 5.2.6 on 2025-12-07 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_tax_number_vehicledetails_vehicleimages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_of_work_eligibility', models.ImageField(blank=True, help_text='Photo of proof of work eligibility document', null=True, upload_to='driver_documents/proof_of_work/', verbose_name='Proof of Work Eligibility')),
                ('profile_photo', models.ImageField(blank=True, help_text='Driver profile photo (verified by Veriff)', null=True, upload_to='driver_documents/profile_photos/', verbose_name='Profile Photo')),
                ('drivers_license', models.ImageField(blank=True, help_text="Photo of driver's license (Class 1, 2, or 4 required)", null=True, upload_to='driver_documents/drivers_license/', verbose_name="Driver's License")),
                ('background_check', models.ImageField(blank=True, help_text='Photo of background check results', null=True, upload_to='driver_documents/background_check/', verbose_name='Background Check')),
                ('driver_abstract', models.ImageField(blank=True, help_text='Photo of province driver abstract (3-year Personal Driver Abstract)', null=True, upload_to='driver_documents/driver_abstract/', verbose_name='Driver Abstract')),
                ('livery_vehicle_registration', models.ImageField(blank=True, help_text='Photo of livery vehicle registration (Class 1-55 or Class 1-66)', null=True, upload_to='driver_documents/livery_registration/', verbose_name='Livery Vehicle Registration')),
                ('vehicle_insurance', models.ImageField(blank=True, help_text='Photo of vehicle insurance document', null=True, upload_to='driver_documents/vehicle_insurance/', verbose_name='Vehicle Insurance')),
                ('city_tndl', models.ImageField(blank=True, help_text='Photo of City TNDL (Taxi Network Driver License)', null=True, upload_to='driver_documents/city_tndl/', verbose_name='City TNDL')),
                ('elvis_vehicle_inspection', models.ImageField(blank=True, help_text='Photo of ELVIS (Enhanced Livery Vehicle Inspection Standards) certificate', null=True, upload_to='driver_documents/elvis_inspection/', verbose_name='ELVIS Vehicle Inspection Form')),
                ('terms_and_conditions', models.BooleanField(default=False, help_text='Whether driver has agreed to terms and conditions', verbose_name='Terms and Conditions')),
                ('legal_agreements', models.BooleanField(default=False, help_text='Whether driver has agreed to legal agreements', verbose_name='Legal Agreements')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(help_text='Driver who owns these identification documents', on_delete=django.db.models.deletion.CASCADE, related_name='driver_identification', to=settings.AUTH_USER_MODEL, verbose_name='Driver')),
            ],
            options={
                'verbose_name': 'Driver Identification',
                'verbose_name_plural': 'Driver Identifications',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user'], name='driver_id_user_idx'), models.Index(fields=['updated_at'], name='driver_id_updated_idx'), models.Index(fields=['user', 'updated_at'], name='driver_id_user_updated_idx'), models.Index(fields=['terms_and_conditions'], name='driver_id_terms_idx'), models.Index(fields=['legal_agreements'], name='driver_id_legal_idx')],
            },
        ),
    ]
