# Generated by Django 5.2.6 on 2025-12-15 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_driveridentification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverIdentificationItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(help_text='Item name or description', max_length=255, verbose_name='Item')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Driver Identification Item',
                'verbose_name_plural': 'Driver Identification Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverIdentificationUploadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.ImageField(help_text='Uploaded document file', upload_to='driver_documents/', verbose_name='Document File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Driver Identification Upload Document',
                'verbose_name_plural': 'Driver Identification Upload Documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='driveridentification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Driver Identification', 'verbose_name_plural': 'Driver Identifications'},
        ),
        migrations.RemoveIndex(
            model_name='driveridentification',
            name='driver_id_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='driveridentification',
            name='driver_id_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='driveridentification',
            name='driver_id_user_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='driveridentification',
            name='driver_id_terms_idx',
        ),
        migrations.RemoveIndex(
            model_name='driveridentification',
            name='driver_id_legal_idx',
        ),
        migrations.RemoveField(
            model_name='driveridentification',
            name='background_check',
        ),
        migrations.RemoveField(
            model_name='driveridentification',
            name='city_tndl',
        ),
        migrations.RemoveField(
            model_name='driveridentification',
            name='driver_abstract',
        ),
        migrations.RemoveField(
            model_name='driveridentification',
            name='drivers_license',
        ),
        migrations.RemoveField(
            model_name='driveridentification',
            name='elvis_vehicle_inspection',
        ),
        migrations.RemoveField(
            model_name='driveridentification',
            name='legal_agreements',
        ),
        migrations.RemoveField(
            model_name='driveridentification',
            name='livery_vehicle_registration',
        ),
        migrations.RemoveField(
            model_name='driveridentification',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='driveridentification',
            name='proof_of_work_eligibility',
        ),
        migrations.RemoveField(
            model_name='driveridentification',
            name='terms_and_conditions',
        ),
        migrations.RemoveField(
            model_name='driveridentification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='driveridentification',
            name='vehicle_insurance',
        ),
        migrations.AddField(
            model_name='driveridentification',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description/instructions for the user', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='driveridentification',
            name='image',
            field=models.ImageField(blank=True, help_text='Icon image for the identification type', null=True, upload_to='driver_identification_icons/', verbose_name='Icon Image'),
        ),
        migrations.AddField(
            model_name='driveridentification',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this identification type is active and visible to users', verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='driveridentification',
            name='name',
            field=models.CharField(default=1, help_text="Unique name for the identification type (e.g., 'Driver License', 'Profile Photo')", max_length=255, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driveridentification',
            name='title',
            field=models.CharField(default=1, help_text="Title to display (e.g., 'Take a photo of your Driver's License')", max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='driveridentification',
            index=models.Index(fields=['name'], name='driver_id_name_idx'),
        ),
        migrations.AddIndex(
            model_name='driveridentification',
            index=models.Index(fields=['is_active'], name='driver_id_active_idx'),
        ),
        migrations.AddIndex(
            model_name='driveridentification',
            index=models.Index(fields=['created_at'], name='driver_id_created_idx'),
        ),
        migrations.AddIndex(
            model_name='driveridentification',
            index=models.Index(fields=['is_active', 'created_at'], name='driver_id_active_created_idx'),
        ),
        migrations.AddField(
            model_name='driveridentificationitems',
            name='driver_identification',
            field=models.ForeignKey(help_text='The identification type this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.driveridentification', verbose_name='Driver Identification'),
        ),
        migrations.AddField(
            model_name='driveridentificationuploaddocument',
            name='driver_identification',
            field=models.ForeignKey(help_text='The identification type this document is for', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='accounts.driveridentification', verbose_name='Driver Identification'),
        ),
        migrations.AddField(
            model_name='driveridentificationuploaddocument',
            name='user',
            field=models.ForeignKey(help_text='User who uploaded the document', on_delete=django.db.models.deletion.CASCADE, related_name='driver_identification_uploads', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='driveridentificationitems',
            index=models.Index(fields=['driver_identification'], name='driver_id_item_id_idx'),
        ),
        migrations.AddIndex(
            model_name='driveridentificationitems',
            index=models.Index(fields=['created_at'], name='driver_id_item_created_idx'),
        ),
        migrations.AddIndex(
            model_name='driveridentificationuploaddocument',
            index=models.Index(fields=['user'], name='driver_upload_user_idx'),
        ),
        migrations.AddIndex(
            model_name='driveridentificationuploaddocument',
            index=models.Index(fields=['driver_identification'], name='driver_upload_id_idx'),
        ),
        migrations.AddIndex(
            model_name='driveridentificationuploaddocument',
            index=models.Index(fields=['user', 'driver_identification'], name='driver_upload_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='driveridentificationuploaddocument',
            index=models.Index(fields=['updated_at'], name='driver_upload_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='driveridentificationuploaddocument',
            constraint=models.UniqueConstraint(fields=('user', 'driver_identification'), name='unique_user_driver_identification'),
        ),
    ]
