# Generated by Django 5.2.6 on 2025-12-15 06:17

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_driveridentificationitems_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverUser',
            fields=[
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RiderUser',
            fields=[
            ],
            options={
                'verbose_name': 'Rider',
                'verbose_name_plural': 'Riders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': '01. Users'},
        ),
        migrations.AlterModelOptions(
            name='driverpreferences',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Driver Preference', 'verbose_name_plural': '03. Driver Preferences'},
        ),
        migrations.AlterModelOptions(
            name='pinverificationforuser',
            options={'ordering': ['-updated_at'], 'verbose_name': 'PIN Verification For User', 'verbose_name_plural': '04. PIN Verifications For Riders'},
        ),
        migrations.AlterModelOptions(
            name='userpreferences',
            options={'ordering': ['-updated_at'], 'verbose_name': 'User Preference', 'verbose_name_plural': '02. Rider Preferences'},
        ),
    ]
