# Generated by Django 5.2.6 on 2025-12-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_driveruser_rideruser_alter_customuser_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driveridentification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Driver Identification', 'verbose_name_plural': '03. Driver Identifications'},
        ),
        migrations.AlterModelOptions(
            name='driveruser',
            options={'verbose_name': 'Driver', 'verbose_name_plural': '02. Drivers'},
        ),
        migrations.AlterModelOptions(
            name='rideruser',
            options={'verbose_name': 'Rider', 'verbose_name_plural': '01. Riders'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_identification',
            field=models.CharField(blank=True, help_text='Unique 9-digit identification number (auto-generated)', max_length=9, null=True, unique=True, verbose_name='ID Identification'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['id_identification'], name='user_id_identification_idx'),
        ),
    ]
