# Generated by Django 5.2.6 on 2025-12-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_driveridentification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveridentificationuploaddocument',
            name='document_file',
            field=models.FileField(help_text='Uploaded document file (any file type)', upload_to='driver_documents/', verbose_name='Document File'),
        ),
    ]
