# Generated by Django 5.2.6 on 2025-12-15 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_driveridentificationuploaddocument_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_submitted', 'Not submitted'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', help_text='Current verification status', max_length=20, verbose_name='Status')),
                ('comment', models.TextField(blank=True, help_text='Optional reviewer comment', null=True, verbose_name='Comment')),
                ('estimated_review_hours', models.IntegerField(default=48, help_text='Estimated review time in hours', verbose_name='Estimated Review Hours')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when status was last set to Approved/Rejected', null=True, verbose_name='Reviewed At')),
                ('reviewer', models.ForeignKey(blank=True, help_text='Admin/staff user who last reviewed this driver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_drivers', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
                ('user', models.OneToOneField(help_text='Driver this verification belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='driver_verification', to=settings.AUTH_USER_MODEL, verbose_name='Driver')),
            ],
            options={
                'verbose_name': 'Driver Verification',
                'verbose_name_plural': 'Driver Verifications',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user'], name='driver_ver_user_idx'), models.Index(fields=['status'], name='driver_ver_status_idx'), models.Index(fields=['updated_at'], name='driver_ver_updated_idx'), models.Index(fields=['user', 'status'], name='driver_ver_user_status_idx')],
            },
        ),
    ]
