# Generated by Django 5.2.6 on 2025-12-15 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_driververification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Push notification token (FCM/APNs/etc.)', max_length=512, verbose_name='Device Token')),
                ('mobile', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], help_text='Device type / platform', max_length=20, verbose_name='Device Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Device Token',
                'verbose_name_plural': 'User Device Tokens',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user'], name='device_token_user_idx'), models.Index(fields=['mobile'], name='device_token_mobile_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'mobile'), name='unique_user_mobile_device_token')],
            },
        ),
    ]
