# Generated by Django 5.2.6 on 2025-12-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userdevicetoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driververification',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Driver Verification', 'verbose_name_plural': '04. Driver Verifications'},
        ),
    ]
