# Generated by Django 5.2.6 on 2025-12-16 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_driververification_options'),
        ('order', '0006_orderschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetails',
            name='default_ride_type',
            field=models.ForeignKey(blank=True, help_text='Primary/default ride type for this vehicle (shown first)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_vehicles', to='order.ridetype', verbose_name='Default Ride Type'),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='supported_ride_types',
            field=models.ManyToManyField(blank=True, help_text='Ride types this vehicle can support (e.g., Standard, Premium, Eco). One vehicle can support multiple types.', related_name='supported_vehicles', to='order.ridetype', verbose_name='Supported Ride Types'),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='vehicle_condition',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair')], default='good', help_text='Condition of the vehicle (affects ride type suggestions)', max_length=20, verbose_name='Vehicle Condition'),
        ),
        migrations.AddIndex(
            model_name='vehicledetails',
            index=models.Index(fields=['vehicle_condition'], name='vehicle_condition_idx'),
        ),
    ]
