# Generated by Django 5.2.6 on 2025-12-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_vehicle_ride_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Indicates whether driver is online and available for orders.', verbose_name='Driver Online Status'),
        ),
    ]
