# Generated by Django 5.2.6 on 2025-12-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_customuser_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetails',
            name='color',
            field=models.CharField(blank=True, help_text='Vehicle color (e.g., White, Black, Red)', max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='plate_number',
            field=models.CharField(blank=True, help_text='Vehicle license plate number (e.g., NYC 560)', max_length=20, null=True, verbose_name='Plate Number'),
        ),
    ]
