# Generated by Django 5.2.6 on 2026-02-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_vehicledetails_color_vehicledetails_plate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveridentification',
            name='file',
            field=models.FileField(blank=True, help_text='Optional file for the identification type', null=True, upload_to='driver_identification_files/', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='driveridentification',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link for the identification type', max_length=500, null=True, verbose_name='Link'),
        ),
    ]
