# Generated by Django 5.2.6 on 2026-02-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_driver_id_file_link_add_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveridentification',
            name='display_type',
            field=models.CharField(choices=[('upload', 'Photo Upload'), ('terms', 'Terms and Conditions')], default='upload', help_text='Whether to display a photo upload or only terms and conditions', max_length=20, verbose_name='Display Type'),
        ),
        migrations.DeleteModel(
            name='DriverIdentificationFAQ',
        ),
    ]
