# Generated by Django 5.2.6 on 2026-02-17 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_driveridentification_display_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driveridentificationitems',
            options={'ordering': ['-created_at'], 'verbose_name': 'Driver Identification Item', 'verbose_name_plural': 'Driver Identification Items (Type: Upload)'},
        ),
        migrations.CreateModel(
            name='DriverIdentificationFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='FAQ question text', max_length=500, verbose_name='Question')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link')),
                ('file', models.FileField(blank=True, null=True, upload_to='driver_identification_faq_files/', verbose_name='File')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower first)', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver_identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identification_faq', to='accounts.driveridentification', verbose_name='Driver Identification')),
            ],
            options={
                'verbose_name': 'Driver Identification FAQ',
                'verbose_name_plural': 'Driver Identification FAQs',
                'ordering': ['order', 'id'],
            },
        ),
    ]
