# Generated by Django 5.2.6 on 2026-02-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_driveridentificationitems_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the agreement', max_length=255, verbose_name='Name')),
                ('file', models.FileField(help_text='File of the agreement', upload_to='driver_agreements/', verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Driver Agreement',
                'verbose_name_plural': '05. Driver Agreements',
                'ordering': ['-updated_at'],
            },
        ),
    ]
