# Generated by Django 5.2.6 on 2026-02-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_driveragreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveragreement',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this agreement is visible to drivers', verbose_name='Is Active'),
        ),
    ]
