# Generated by Django 5.2.6 on 2026-02-27 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_add_is_active_to_driveragreement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalpage',
            options={'ordering': ['name'], 'verbose_name': 'Legal Agreement', 'verbose_name_plural': 'Legal Agreements'},
        ),
        migrations.CreateModel(
            name='AcceptanceOfAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=True, help_text='Whether this agreement is accepted by the user', verbose_name='Is Accepted')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_of_agreements', to='accounts.legalpage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_of_agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceptance of Agreement',
                'verbose_name_plural': 'Acceptance of Agreements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='acc_agree_user_idx'), models.Index(fields=['agreement'], name='acc_agree_agmt_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'agreement'), name='unique_user_agreement_acceptance')],
            },
        ),
    ]
