# Generated by Django 5.2.6 on 2026-02-27 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_legalpage_options_acceptanceofagreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditionsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=True, verbose_name='Is Accepted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver_identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_and_conditions_acceptance', to='accounts.driveridentification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_and_conditions_acceptance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terms and Conditions Acceptance',
                'verbose_name_plural': 'Terms and Conditions Acceptances',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='terms_accept_user_idx'), models.Index(fields=['driver_identification'], name='terms_accept_id_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'driver_identification'), name='terms_accept_user_di_uniq')],
            },
        ),
    ]
