# Generated by Django 5.2.6 on 2026-04-03 04:56

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_legalpage_page_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalpage',
            name='terms_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Used when Page kind is Terms and conditions. Rich text for in-app scroll view.', verbose_name='Terms body (HTML)'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='link',
            field=models.URLField(blank=True, help_text='URL to the document (required for Legal agreement only; not used for Terms)', max_length=500, null=True, verbose_name='Link'),
        ),
    ]
