# Generated by Django 5.2.6 on 2026-04-06 09:49

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_legalpage_terms_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalpage',
            name='link',
            field=models.URLField(blank=True, help_text='URL to the document (required for Legal agreement only; not used for terms / registration_terms)', max_length=500, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='page_kind',
            field=models.CharField(choices=[('terms', 'Terms and conditions (driver)'), ('registration_terms', 'Registration terms (rider Open terms)'), ('legal_agreement', 'Legal agreement')], default='legal_agreement', help_text='terms = full scroll T&C + Accept/Decline (driver). registration_terms = signup “Open terms” copy (rider). legal_agreement = list + Yes I agree (Hola Agreement 1, 2).', max_length=30, verbose_name='Page kind'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='terms_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='HTML for page_kind terms or registration_terms (in-app / WebView).', verbose_name='Terms body (HTML)'),
        ),
    ]
