# Generated by Django 5.2.6 on 2026-04-06 20:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_remove_driver_identification_stack'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverIdentificationAgreementsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(help_text='Rich text (HTML) for this agreement item', verbose_name='Content')),
                ('file', models.FileField(blank=True, null=True, upload_to='driver_identification_agreements/', verbose_name='File')),
                ('item_type', models.CharField(choices=[('terms', 'Terms and Conditions Acceptance'), ('legal', 'Legal Agreements Acceptance'), ('registration', 'Registration Terms Acceptance')], max_length=20, verbose_name='Item type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Driver Identification Agreements Item',
                'verbose_name_plural': 'Driver Identification Agreements Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='driveridentificationagreementsitems',
            index=models.Index(fields=['item_type'], name='drv_id_agg_item_type_idx'),
        ),
        migrations.AddIndex(
            model_name='driveridentificationagreementsitems',
            index=models.Index(fields=['created_at'], name='drv_id_agg_created_idx'),
        ),
    ]
