# Generated by Django 5.2.6 on 2026-04-06 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_driveridentificationagreementsitems_parent_gfk'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title to display (e.g., 'Take a photo of your Driver's License')", max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Detailed description/instructions for the user', null=True, verbose_name='Description')),
                ('display_type', models.CharField(choices=[('upload', 'Photo Upload'), ('terms', 'Terms and Conditions Acceptance'), ('legal', 'Legal Agreements Acceptance'), ('registration', 'Registration Terms Acceptance')], default='upload', help_text='Whether to display a photo upload or only terms and conditions', max_length=20, verbose_name='Display Type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this identification type is active and visible to users', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Driver Identification',
                'verbose_name_plural': '03. Driver Identifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverIdentificationUploadTypeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(help_text='Item name or description', max_length=255, verbose_name='Item')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Driver Identification Upload Type Item',
                'verbose_name_plural': 'Driver Identification Upload Type Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverIdentificationUploadTypeQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Question text', max_length=255, verbose_name='Question')),
                ('file', models.FileField(help_text='File', upload_to='driver_identification_upload_type_question_answers/', verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Driver Identification Upload Type Question Answer',
                'verbose_name_plural': 'Driver Identification Upload Type Question Answers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverIdentificationLegalType',
            fields=[
                ('driveridentification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.driveridentification')),
            ],
            options={
                'verbose_name': 'Driver identification — legal agreements',
                'verbose_name_plural': '06. Driver identification — legal agreements',
                'ordering': ['-created_at'],
            },
            bases=('accounts.driveridentification',),
        ),
        migrations.CreateModel(
            name='DriverIdentificationRegistrationType',
            fields=[
                ('driveridentification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.driveridentification')),
            ],
            options={
                'verbose_name': 'Driver identification — registration',
                'verbose_name_plural': '07. Driver identification — registration terms',
                'ordering': ['-created_at'],
            },
            bases=('accounts.driveridentification',),
        ),
        migrations.CreateModel(
            name='DriverIdentificationTermsType',
            fields=[
                ('driveridentification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.driveridentification')),
            ],
            options={
                'verbose_name': 'Driver identification — terms',
                'verbose_name_plural': '08. Driver identification — terms & conditions',
                'ordering': ['-created_at'],
            },
            bases=('accounts.driveridentification',),
        ),
        migrations.CreateModel(
            name='DriverIdentificationUploadType',
            fields=[
                ('driveridentification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.driveridentification')),
                ('icon', models.ImageField(help_text='Icon image for the identification type', upload_to='driver_identification_upload_type_icons/', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Driver identification — upload',
                'verbose_name_plural': '05. Driver identification — upload (photos & documents)',
                'ordering': ['-created_at'],
            },
            bases=('accounts.driveridentification',),
        ),
        migrations.AddIndex(
            model_name='driveridentification',
            index=models.Index(fields=['title'], name='driver_id_title_idx'),
        ),
        migrations.AddIndex(
            model_name='driveridentification',
            index=models.Index(fields=['is_active'], name='driver_id_active_idx'),
        ),
        migrations.AddIndex(
            model_name='driveridentification',
            index=models.Index(fields=['created_at'], name='driver_id_created_idx'),
        ),
        migrations.AddIndex(
            model_name='driveridentification',
            index=models.Index(fields=['is_active', 'created_at'], name='driver_id_active_created_idx'),
        ),
        migrations.AddField(
            model_name='driveridentificationuploadtypequestionanswer',
            name='driver_identification_upload_type_item',
            field=models.ForeignKey(help_text='Driver Identification Upload Type Item this question answer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='accounts.driveridentificationuploadtypeitem', verbose_name='Driver Identification Upload Type Item'),
        ),
        migrations.AddField(
            model_name='driveridentificationuploadtypeitem',
            name='driver_identification_upload_type',
            field=models.ForeignKey(help_text='Driver Identification Upload Type this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.driveridentificationuploadtype', verbose_name='Driver Identification Upload Type'),
        ),
        migrations.AddIndex(
            model_name='driveridentificationuploadtypequestionanswer',
            index=models.Index(fields=['driver_identification_upload_type_item'], name='driver_id_upload_type_item_idx'),
        ),
        migrations.AddIndex(
            model_name='driveridentificationuploadtypeitem',
            index=models.Index(fields=['driver_identification_upload_type'], name='driver_id_upload_type_idx'),
        ),
    ]
