# Generated by Django 5.2.6 on 2026-04-06 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_recreate_driver_identification_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driveridentificationlegaltype',
            options={'ordering': ['-created_at'], 'verbose_name': 'Driver identification — legal agreements', 'verbose_name_plural': '06. Legal — driver identification (agreements)'},
        ),
        migrations.AlterModelOptions(
            name='driveridentificationregistrationtype',
            options={'ordering': ['-created_at'], 'verbose_name': 'Driver identification — registration', 'verbose_name_plural': '07. Registration — driver identification (terms)'},
        ),
        migrations.AlterModelOptions(
            name='driveridentificationtermstype',
            options={'ordering': ['-created_at'], 'verbose_name': 'Driver identification — terms', 'verbose_name_plural': '08. Terms — driver identification (T&C)'},
        ),
        migrations.AlterModelOptions(
            name='driveridentificationuploadtype',
            options={'ordering': ['-created_at'], 'verbose_name': 'Driver identification — upload', 'verbose_name_plural': '05. Upload — driver identification (photos & documents)'},
        ),
        migrations.AlterModelOptions(
            name='driververification',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Driver Verification', 'verbose_name_plural': '04. Verification — drivers (status / KYC)'},
        ),
        migrations.CreateModel(
            name='DriverIdentificationLegalAgreementsUserAccepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False, help_text='Whether this driver identification legal agreements is accepted by the user', verbose_name='Is Accepted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('driver_identification_legal_agreements', models.ForeignKey(help_text='Driver Identification Legal Agreements this user accepted belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='user_accepted', to='accounts.driveridentificationlegaltype', verbose_name='Driver Identification Legal Agreements')),
                ('user', models.ForeignKey(help_text='User who accepted this driver identification legal agreements', on_delete=django.db.models.deletion.CASCADE, related_name='driver_legal_agreement_acceptances', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Driver Identification Legal Agreements User Accepted',
                'verbose_name_plural': 'Driver Identification Legal Agreements User Accepted',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver_identification_legal_agreements'], name='di_lgua_agr_idx'), models.Index(fields=['user'], name='di_lgua_user_idx'), models.Index(fields=['created_at'], name='di_lgua_created_idx'), models.Index(fields=['driver_identification_legal_agreements', 'user'], name='di_lgua_agr_usr_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverIdentificationRegistrationAgreementsUserAccepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False, help_text='Whether this driver identification registration agreements is accepted by the user', verbose_name='Is Accepted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('driver_identification_registration_agreements', models.ForeignKey(help_text='Driver Identification Registration Agreements this user accepted belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='user_accepted', to='accounts.driveridentificationregistrationtype', verbose_name='Driver Identification Registration Agreements')),
                ('user', models.ForeignKey(help_text='User who accepted this driver identification registration agreements', on_delete=django.db.models.deletion.CASCADE, related_name='driver_registration_agreement_acceptances', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Driver Identification Registration Agreements User Accepted',
                'verbose_name_plural': 'Driver Identification Registration Agreements User Accepted',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver_identification_registration_agreements'], name='di_rgua_agr_idx'), models.Index(fields=['user'], name='di_rgua_user_idx'), models.Index(fields=['created_at'], name='di_rgua_created_idx'), models.Index(fields=['driver_identification_registration_agreements', 'user'], name='di_rgua_agr_usr_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverIdentificationTermsUserAccepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False, help_text='Whether this driver identification terms is accepted by the user', verbose_name='Is Accepted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('driver_identification_terms', models.ForeignKey(help_text='Driver Identification Terms this user accepted belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='user_accepted', to='accounts.driveridentificationtermstype', verbose_name='Driver Identification Terms')),
                ('user', models.ForeignKey(help_text='User who accepted this driver identification terms', on_delete=django.db.models.deletion.CASCADE, related_name='driver_terms_acceptances', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Driver Identification Terms User Accepted',
                'verbose_name_plural': 'Driver Identification Terms User Accepted',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver_identification_terms'], name='di_tmua_term_idx'), models.Index(fields=['user'], name='di_tmua_user_idx'), models.Index(fields=['created_at'], name='di_tmua_created_idx'), models.Index(fields=['driver_identification_terms', 'user'], name='di_tmua_term_usr_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverIdentificationUploadTypeUserAccepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='File', upload_to='driver_identification_upload_type_user_accepted/', verbose_name='File')),
                ('is_accepted', models.BooleanField(default=False, help_text='Whether this driver identification upload type is accepted by the user', verbose_name='Is Accepted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('driver_identification_upload_type', models.ForeignKey(help_text='Driver Identification Upload Type this user accepted belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='user_accepted', to='accounts.driveridentificationuploadtype', verbose_name='Driver Identification Upload Type')),
                ('user', models.ForeignKey(help_text='User who accepted this driver identification upload type', on_delete=django.db.models.deletion.CASCADE, related_name='driver_upload_type_acceptances', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Driver Identification Upload Type User Accepted',
                'verbose_name_plural': 'Driver Identification Upload Type User Accepted',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver_identification_upload_type'], name='di_utua_type_idx'), models.Index(fields=['user'], name='di_utua_user_idx'), models.Index(fields=['created_at'], name='di_utua_created_idx'), models.Index(fields=['driver_identification_upload_type', 'user'], name='di_utua_type_usr_idx')],
            },
        ),
    ]
