# Generated by Django 5.2.6 on 2026-04-06 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_driver_identification_user_accepted_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverIdentificationTermsItemUserAccepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Is accepted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Driver Identification Terms Item User Accepted',
                'verbose_name_plural': 'Driver Identification Terms Item User Accepted',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='driveridentificationuploadtypeuseraccepted',
            name='question_answer',
            field=models.ForeignKey(blank=True, help_text='When set, this row stores the user upload for that checklist slot. When null, a single file covers the whole upload step (no per-slot questions).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_acceptances', to='accounts.driveridentificationuploadtypequestionanswer', verbose_name='Question / attachment slot'),
        ),
        migrations.AddIndex(
            model_name='driveridentificationuploadtypeuseraccepted',
            index=models.Index(fields=['question_answer'], name='di_utua_qa_idx'),
        ),
        migrations.AddConstraint(
            model_name='driveridentificationuploadtypeuseraccepted',
            constraint=models.UniqueConstraint(condition=models.Q(('question_answer__isnull', False)), fields=('user', 'question_answer'), name='di_utua_usr_qa_uniq'),
        ),
        migrations.AddConstraint(
            model_name='driveridentificationuploadtypeuseraccepted',
            constraint=models.UniqueConstraint(condition=models.Q(('question_answer__isnull', True)), fields=('user', 'driver_identification_upload_type'), name='di_utua_usr_type_nullqa_uniq'),
        ),
        migrations.AddField(
            model_name='driveridentificationtermsitemuseraccepted',
            name='agreement_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_item_user_acceptances', to='accounts.driveridentificationagreementsitems', verbose_name='Agreement item'),
        ),
        migrations.AddField(
            model_name='driveridentificationtermsitemuseraccepted',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_terms_item_acceptances', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='driveridentificationtermsitemuseraccepted',
            index=models.Index(fields=['user'], name='di_tiua_user_idx'),
        ),
        migrations.AddIndex(
            model_name='driveridentificationtermsitemuseraccepted',
            index=models.Index(fields=['agreement_item'], name='di_tiua_agr_idx'),
        ),
        migrations.AddIndex(
            model_name='driveridentificationtermsitemuseraccepted',
            index=models.Index(fields=['created_at'], name='di_tiua_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='driveridentificationtermsitemuseraccepted',
            constraint=models.UniqueConstraint(fields=('user', 'agreement_item'), name='di_tiua_usr_agr_uniq'),
        ),
    ]
