# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_driver_identification_checklist_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_connect_account_id',
            field=models.CharField(
                blank=True,
                help_text='Connected account id (acct_…) for trip payouts; optional until Connect onboarding.',
                max_length=255,
                verbose_name='Stripe Connect account',
            ),
        ),
    ]
