# Generated by Django 5.0.7 on 2026-07-25 10:11

import apps.safety.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0027_initial_safety_tools'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(help_text='Staff/admin handling safety chats', on_delete=django.db.models.deletion.CASCADE, related_name='safety_rooms_as_agent', to=settings.AUTH_USER_MODEL)),
                ('orders', models.ManyToManyField(blank=True, related_name='safety_rooms', to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Safety Room',
                'verbose_name_plural': '02 Safety Rooms',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('system', 'System')], default='user', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_messages', to='order.order')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_messages_sent', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='safety.safetyroom')),
            ],
            options={
                'verbose_name': 'Safety Message',
                'verbose_name_plural': '03 Safety Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=apps.safety.models._share_token, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_share_links', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='order.order')),
            ],
            options={
                'verbose_name': 'Trip Share Link',
                'verbose_name_plural': '01 Trip Share Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripVoiceRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('uploaded', 'Uploaded'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='recording', max_length=20)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=apps.safety.models.trip_recording_upload_to)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_voice_recordings', to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_voice_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip Voice Recording',
                'verbose_name_plural': '04 Trip Voice Recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='safetyroom',
            index=models.Index(fields=['user'], name='safetyroom_user_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyroom',
            index=models.Index(fields=['agent'], name='safetyroom_agent_idx'),
        ),
        migrations.AddConstraint(
            model_name='safetyroom',
            constraint=models.UniqueConstraint(fields=('user', 'agent'), name='safety_room_user_agent_uniq'),
        ),
        migrations.AddIndex(
            model_name='safetymessage',
            index=models.Index(fields=['room', 'created_at'], name='safetymsg_room_created_idx'),
        ),
        migrations.AddIndex(
            model_name='tripsharelink',
            index=models.Index(fields=['order', 'is_active'], name='tripshare_order_active_idx'),
        ),
        migrations.AddIndex(
            model_name='tripsharelink',
            index=models.Index(fields=['expires_at'], name='tripshare_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='tripvoicerecording',
            index=models.Index(fields=['order', 'status'], name='triprec_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tripvoicerecording',
            index=models.Index(fields=['user'], name='triprec_user_idx'),
        ),
    ]
