# Generated by Django 5.0.7 on 2026-07-02 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0004_support_rooms'),
        ('order', '0025_latlon_precision_18'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportAgentDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on_duty', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_agent_duty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Agent Duty',
                'verbose_name_plural': 'Support Agent Duties',
            },
        ),
        migrations.CreateModel(
            name='VoiceCallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('trip', 'Trip'), ('rider_support', 'Rider Support'), ('driver_support', 'Driver Support')], max_length=20)),
                ('status', models.CharField(choices=[('ringing', 'Ringing'), ('answered', 'Answered'), ('ended', 'Ended'), ('missed', 'Missed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='ringing', max_length=20)),
                ('agora_channel_name', models.CharField(max_length=128, unique=True)),
                ('agora_app_id', models.CharField(blank=True, max_length=64)),
                ('initiator_role', models.CharField(choices=[('rider', 'Rider'), ('driver', 'Driver'), ('admin', 'Admin')], max_length=20)),
                ('ring_started_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=255)),
                ('operator_note', models.TextField(blank=True, help_text='Admin summary after support call')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('callee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_calls_received', to=settings.AUTH_USER_MODEL)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_calls_made', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_calls', to='order.order')),
                ('support_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_calls', to='chat.supportroom')),
            ],
            options={
                'verbose_name': 'Voice Call Session',
                'verbose_name_plural': 'Voice Call Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_url', models.URLField(blank=True)),
                ('recording_status', models.CharField(choices=[('not_started', 'Not started'), ('recording', 'Recording'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20)),
                ('transcript_text', models.TextField(blank=True)),
                ('transcript_status', models.CharField(choices=[('not_requested', 'Not requested'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_requested', max_length=20)),
                ('agora_resource_id', models.CharField(blank=True, max_length=128)),
                ('agora_sid', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='voice_call.voicecallsession')),
            ],
            options={
                'verbose_name': 'Call Recording',
                'verbose_name_plural': 'Call Recordings',
            },
        ),
        migrations.AddIndex(
            model_name='voicecallsession',
            index=models.Index(fields=['call_type'], name='voicecall_type_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecallsession',
            index=models.Index(fields=['status'], name='voicecall_status_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecallsession',
            index=models.Index(fields=['caller'], name='voicecall_caller_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecallsession',
            index=models.Index(fields=['callee'], name='voicecall_callee_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecallsession',
            index=models.Index(fields=['order'], name='voicecall_order_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecallsession',
            index=models.Index(fields=['created_at'], name='voicecall_created_idx'),
        ),
    ]
