# Generated by Django 5.2.6 on 2025-11-22 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('chat_message', 'Chat Message'), ('order_update', 'Order Update'), ('system', 'System'), ('promotion', 'Promotion'), ('other', 'Other')], default='other', max_length=20, verbose_name='Notification Type')),
                ('title', models.CharField(help_text='Notification title', max_length=255, verbose_name='Title')),
                ('message', models.TextField(help_text='Notification message content', verbose_name='Message')),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], default='unread', max_length=10, verbose_name='Status')),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object (e.g., "order", "conversation")', max_length=50, null=True, verbose_name='Related Object Type')),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID of related object', null=True, verbose_name='Related Object ID')),
                ('data', models.JSONField(blank=True, help_text='Additional data in JSON format', null=True, verbose_name='Data')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when notification was read', null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': '01 Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='notification_user_idx'), models.Index(fields=['status'], name='notification_status_idx'), models.Index(fields=['notification_type'], name='notification_type_idx'), models.Index(fields=['user', 'status'], name='notification_user_status_idx'), models.Index(fields=['created_at'], name='notification_created_idx')],
            },
        ),
    ]
