# Generated by Django 5.2.6 on 2025-11-22 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Order Code')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_passengers', to='order.order')),
            ],
            options={
                'verbose_name': 'Additional Passenger',
                'verbose_name_plural': 'Additional Passengers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pin Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_drivers', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_drivers', to='order.order')),
            ],
            options={
                'verbose_name': 'Order Driver',
                'verbose_name_plural': 'Order Drivers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CancelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('change_in_plans', 'Change in Plans'), ('waiting_for_long_time', 'Waiting for Long Time'), ('driver_denied_to_go_to_destination', 'Driver Denied to Go to Destination'), ('driver_denied_to_come_to_pickup', 'Driver Denied to Come to Pickup'), ('wrong_address_shown', 'Wrong Address Shown'), ('the_price_is_not_reasonable', 'The Price is Not Reasonable'), ('emergency_situation', 'Emergency Situation'), ('other', 'Other')], default='other', max_length=255)),
                ('other_reason', models.TextField(blank=True, null=True, verbose_name='Other Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_orders', to='order.order')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_orders', to='order.orderdriver')),
            ],
            options={
                'verbose_name': 'Cancel Order',
                'verbose_name_plural': 'Cancel Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_from', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address From')),
                ('address_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address To')),
                ('latitude_from', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude From')),
                ('longitude_from', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude From')),
                ('latitude_to', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude To')),
                ('longitude_to', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude To')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RideType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('name_large', models.CharField(blank=True, max_length=50, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Base Price')),
                ('price_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price Per KM')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Capacity')),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_ev', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ride Type',
                'verbose_name_plural': 'Ride Types',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='ride_type_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='SurgePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='1.00 = normal, 1.5 = 50% increase, 0.8 = 20% decrease', max_digits=5, verbose_name='Multiplier')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('days_of_week', models.JSONField(default=list, help_text='[0,1,2,3,4] - Monday to Friday', verbose_name='Days of Week')),
                ('zone_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zone Name')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('radius_km', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Radius (KM)')),
                ('min_available_drivers', models.IntegerField(blank=True, null=True, verbose_name='Min Available Drivers')),
                ('max_available_drivers', models.IntegerField(blank=True, null=True, verbose_name='Max Available Drivers')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('priority', models.IntegerField(default=0, help_text='Which one is checked first', verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Surge Pricing',
                'verbose_name_plural': 'Surge Pricings',
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='surge_active_priority_idx'), models.Index(fields=['latitude', 'longitude'], name='surge_location_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='order_user_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='order_created_idx'),
        ),
        migrations.AddIndex(
            model_name='additionalpassenger',
            index=models.Index(fields=['order'], name='add_pass_order_idx'),
        ),
        migrations.AddIndex(
            model_name='additionalpassenger',
            index=models.Index(fields=['created_at'], name='add_pass_created_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdriver',
            index=models.Index(fields=['order'], name='order_driver_order_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdriver',
            index=models.Index(fields=['driver'], name='order_driver_driver_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdriver',
            index=models.Index(fields=['created_at'], name='order_driver_created_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='order_item_order_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['created_at'], name='order_item_created_idx'),
        ),
    ]
