# Generated by Django 5.2.6 on 2025-11-22 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalpassenger',
            options={'ordering': ['-created_at'], 'verbose_name': 'Additional Passenger', 'verbose_name_plural': '04 Additional Passengers'},
        ),
        migrations.AlterModelOptions(
            name='cancelorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cancel Order', 'verbose_name_plural': '07 Cancel Orders'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': '01 Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderdriver',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order Driver', 'verbose_name_plural': '05 Order Drivers'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order Item', 'verbose_name_plural': '03 Order Items'},
        ),
        migrations.AlterModelOptions(
            name='ridetype',
            options={'ordering': ['name'], 'verbose_name': 'Ride Type', 'verbose_name_plural': '02 Ride Types'},
        ),
        migrations.AlterModelOptions(
            name='surgepricing',
            options={'ordering': ['-priority', 'name'], 'verbose_name': 'Surge Pricing', 'verbose_name_plural': '06 Surge Pricings'},
        ),
        migrations.CreateModel(
            name='OrderPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatting_preference', models.CharField(choices=[('no_communication', 'No Communication'), ('casual', 'Casual'), ('friendly', 'Friendly')], default='no_communication', max_length=20)),
                ('temperature_preference', models.CharField(choices=[('warm', 'Warm (25°C and above)'), ('comfortable', 'Comfortable (22-24°C)'), ('cool', 'Cool (18-21°C)'), ('cold', 'Cold (below 18°C)')], default='comfortable', max_length=20)),
                ('music_preference', models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('hip_hop', 'Hip Hop'), ('electronic', 'Electronic'), ('country', 'Country'), ('no_music', 'No Music')], default='pop', max_length=20)),
                ('volume_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('mute', 'Mute')], default='medium', max_length=10)),
                ('pet_preference', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
                ('kids_chair_preference', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
                ('wheelchair_preference', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
                ('gender_preference', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=20)),
                ('favorite_driver_preference', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_preferences', to='order.order')),
            ],
            options={
                'verbose_name': 'Order Preferences',
                'verbose_name_plural': '04 Order Preferences',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='order_preferences_order_idx'), models.Index(fields=['created_at'], name='order_preferences_created_idx')],
            },
        ),
    ]
