# Generated by Django 5.2.6 on 2025-11-22 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_additionalpassenger_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='adjusted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price after user adjustment (manage price)', max_digits=10, null=True, verbose_name='Adjusted Price'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='calculated_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Automatically calculated price based on distance and surge', max_digits=10, null=True, verbose_name='Calculated Price'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distance (KM)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Estimated Time'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_price_adjusted',
            field=models.BooleanField(default=False, help_text='Whether user has adjusted the price', verbose_name='Is Price Adjusted'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed price (e.g., 150% of original)', max_digits=10, null=True, verbose_name='Max Price'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum allowed price (e.g., 80% of original)', max_digits=10, null=True, verbose_name='Min Price'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Initial calculated price before user adjustment', max_digits=10, null=True, verbose_name='Original Price'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_adjustment_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage change from original price', max_digits=5, null=True, verbose_name='Price Adjustment %'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ride_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='order.ridetype', verbose_name='Ride Type'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['ride_type'], name='order_item_ride_type_idx'),
        ),
    ]
