# Generated by Django 5.2.6 on 2025-11-22 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_adjusted_price_orderitem_calculated_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-created_at', 'order', 'stop_sequence'], 'verbose_name': 'Order Item', 'verbose_name_plural': '03 Order Items'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_final_stop',
            field=models.BooleanField(default=False, help_text='Whether this is the final destination', verbose_name='Is Final Stop'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stop_sequence',
            field=models.IntegerField(default=1, help_text='Order of stops (1 = first stop, 2 = second stop, etc.)', verbose_name='Stop Sequence'),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique promo code (e.g., SAVE20, WELCOME50)', max_length=50, unique=True, verbose_name='Promo Code')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], default='percentage', max_length=20, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g., 20 for 20%) or Fixed Amount (e.g., 10.00)', max_digits=10, verbose_name='Discount Value')),
                ('max_uses', models.IntegerField(blank=True, help_text='Maximum number of times this code can be used. Null = unlimited.', null=True, verbose_name='Max Uses')),
                ('current_uses', models.IntegerField(default=0, help_text='Number of times this code has been used', verbose_name='Current Uses')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('valid_from', models.DateTimeField(blank=True, help_text='Start date/time for promo code validity', null=True, verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(blank=True, help_text='End date/time for promo code validity', null=True, verbose_name='Valid Until')),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order amount required to use this promo code', max_digits=10, null=True, verbose_name='Minimum Order Amount')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage discounts)', max_digits=10, null=True, verbose_name='Maximum Discount Amount')),
                ('description', models.TextField(blank=True, help_text='Description of the promo code', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(blank=True, help_text="If set, this promo code is only for this specific user. If null, it's general.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': '09 Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Actual discount amount applied to this order', max_digits=10, verbose_name='Discount Amount')),
                ('order_amount_before_discount', models.DecimalField(decimal_places=2, help_text='Order amount before applying discount', max_digits=10, verbose_name='Order Amount Before Discount')),
                ('order_amount_after_discount', models.DecimalField(decimal_places=2, help_text='Order amount after applying discount', max_digits=10, verbose_name='Order Amount After Discount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('applied_by', models.ForeignKey(help_text='User who applied this promo code to the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_promo_codes', to=settings.AUTH_USER_MODEL, verbose_name='Applied By')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_promo_codes', to='order.order', verbose_name='Order')),
                ('promo_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_applications', to='order.promocode', verbose_name='Promo Code')),
            ],
            options={
                'verbose_name': 'Order Promo Code',
                'verbose_name_plural': '10 Order Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPaymentSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_type', models.CharField(choices=[('even', 'Even Split'), ('custom', 'Custom Split')], default='even', help_text='Even split or custom amount', max_length=20, verbose_name='Split Type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount this user needs to pay', max_digits=10, verbose_name='Amount')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of total fare (for custom splits)', max_digits=5, null=True, verbose_name='Percentage')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('invitation_token', models.CharField(blank=True, help_text='Unique token for split fare invitation link', max_length=100, null=True, unique=True, verbose_name='Invitation Token')),
                ('invited_at', models.DateTimeField(blank=True, null=True, verbose_name='Invited At')),
                ('invitation_accepted', models.BooleanField(default=False, help_text='Whether co-rider accepted the split fare invitation', verbose_name='Invitation Accepted')),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Payment Confirmed At')),
                ('payment_failed_reason', models.TextField(blank=True, help_text='Reason if payment failed', null=True, verbose_name='Payment Failed Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_splits', to='order.order', verbose_name='Order')),
                ('user', models.ForeignKey(help_text='User who needs to pay their share', on_delete=django.db.models.deletion.CASCADE, related_name='payment_splits', to=settings.AUTH_USER_MODEL, verbose_name='Co-Rider')),
            ],
            options={
                'verbose_name': 'Order Payment Split',
                'verbose_name_plural': '08 Order Payment Splits',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['order'], name='payment_split_order_idx'), models.Index(fields=['user'], name='payment_split_user_idx'), models.Index(fields=['payment_status'], name='payment_split_status_idx'), models.Index(fields=['invitation_token'], name='payment_split_token_idx'), models.Index(fields=['order', 'payment_status'], name='payment_split_order_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code'], name='promo_code_code_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['user'], name='promo_code_user_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['is_active'], name='promo_code_active_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['valid_from', 'valid_until'], name='promo_code_validity_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpromocode',
            index=models.Index(fields=['order'], name='order_promo_order_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpromocode',
            index=models.Index(fields=['promo_code'], name='order_promo_code_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpromocode',
            index=models.Index(fields=['applied_by'], name='order_promo_applied_by_idx'),
        ),
    ]
