# Generated by Django 5.2.6 on 2025-11-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderitem_options_orderitem_is_final_stop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('for_me', 'For Me')], default='pickup', max_length=20),
        ),
    ]
