# Generated by Django 5.2.6 on 2025-11-24 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('pickup_at', 'Pickup At'), ('drop_off_by', 'Drop Off By')], default='pickup_at', max_length=20)),
                ('schedule_date', models.DateField(blank=True, null=True, verbose_name='Schedule Date')),
                ('schedule_time', models.TimeField(blank=True, null=True, verbose_name='Schedule Time')),
                ('schedule_time_type', models.CharField(choices=[('today', 'Today'), ('tomorrow', 'Tomorrow'), ('select_date', 'Select Date')], default='today', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_schedules', to='order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Schedule',
                'verbose_name_plural': '05 Order Schedules',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='order_schedule_order_idx'), models.Index(fields=['schedule_date'], name='ord_sched_date_idx'), models.Index(fields=['schedule_time'], name='ord_sched_time_idx'), models.Index(fields=['created_at'], name='order_schedule_created_idx')],
            },
        ),
    ]
