# Generated by Django 5.2.6 on 2025-12-16 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdriver',
            name='requested_at',
            field=models.DateTimeField(blank=True, help_text='When this order was first shown / sent to this driver.', null=True, verbose_name='Requested At'),
        ),
        migrations.AddField(
            model_name='orderdriver',
            name='responded_at',
            field=models.DateTimeField(blank=True, help_text='When driver accepted or rejected this order.', null=True, verbose_name='Responded At'),
        ),
        migrations.AddField(
            model_name='orderdriver',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('timeout', 'Timeout')], default='requested', help_text='Driver request status for this order.', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='orderdriver',
            index=models.Index(fields=['status'], name='order_driver_status_idx'),
        ),
    ]
