# Generated by Django 5.2.6 on 2025-12-17 12:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_add_orderdriver_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingFeedbackTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tag name (e.g., 'Professionalism', 'Poor route', 'Dirty')", max_length=100, unique=True, verbose_name='Tag Name')),
                ('tag_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], help_text='Positive tags shown for 4-5 stars, Negative tags for 1-3 stars', max_length=20, verbose_name='Tag Type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tag is active and visible', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Rating Feedback Tag',
                'verbose_name_plural': '11 Rating Feedback Tags',
                'ordering': ['tag_type', 'name'],
                'indexes': [models.Index(fields=['tag_type'], name='rating_tag_type_idx'), models.Index(fields=['is_active'], name='rating_tag_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='TripRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, help_text='Optional comment/feedback text', null=True, verbose_name='Comment')),
                ('tip_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Optional tip amount for the driver', max_digits=10, null=True, verbose_name='Tip Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', help_text='Status of the feedback (for moderation)', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('driver', models.ForeignKey(help_text='Driver who received this rating', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL, verbose_name='Driver')),
                ('feedback_tags', models.ManyToManyField(blank=True, help_text='Selected feedback tags (positive for 4-5 stars, negative for 1-3 stars)', related_name='trip_ratings', to='order.ratingfeedbacktag', verbose_name='Feedback Tags')),
                ('order', models.OneToOneField(help_text='Order this rating belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='trip_rating', to='order.order', verbose_name='Order')),
                ('rider', models.ForeignKey(help_text='Rider who gave this rating', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='Rider')),
            ],
            options={
                'verbose_name': 'Trip Rating',
                'verbose_name_plural': '12 Trip Ratings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='trip_rating_order_idx'), models.Index(fields=['rider'], name='trip_rating_rider_idx'), models.Index(fields=['driver'], name='trip_rating_driver_idx'), models.Index(fields=['rating'], name='trip_rating_rating_idx'), models.Index(fields=['status'], name='trip_rating_status_idx'), models.Index(fields=['created_at'], name='trip_rating_created_idx')],
            },
        ),
    ]
