# Generated by Django 5.2.6 on 2026-03-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_ratingfeedbacktag_triprating'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdriver',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When driver completed the ride (drop-off).', null=True, verbose_name='Completed At'),
        ),
        migrations.AddField(
            model_name='orderdriver',
            name='pickup_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When driver confirmed pickup (client in car).', null=True, verbose_name='Pickup Confirmed At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
