# Generated by Django 5.2.6 on 2026-03-13 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_add_pickup_complete_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelorder',
            name='cancelled_by',
            field=models.CharField(choices=[('rider', 'Rider'), ('driver', 'Driver')], default='rider', help_text='Who cancelled the order (rider or driver)', max_length=20, verbose_name='Cancelled By'),
        ),
        migrations.AlterField(
            model_name='cancelorder',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancel_orders', to='order.orderdriver'),
        ),
        migrations.AlterField(
            model_name='cancelorder',
            name='reason',
            field=models.CharField(choices=[('change_in_plans', 'Change in Plans'), ('waiting_for_long_time', 'Waiting for Long Time'), ('driver_denied_to_go_to_destination', 'Driver Denied to Go to Destination'), ('driver_denied_to_come_to_pickup', 'Driver Denied to Come to Pickup'), ('wrong_address_shown', 'Wrong Address Shown'), ('the_price_is_not_reasonable', 'The Price is Not Reasonable'), ('emergency_situation', 'Emergency Situation'), ('rider_not_at_pickup', 'Rider Not at Pickup Location'), ('rider_asked_to_cancel', 'Rider Asked to Cancel'), ('vehicle_issue', 'Vehicle Issue'), ('safety_concern', 'Safety Concern'), ('other', 'Other')], default='other', max_length=255),
        ),
    ]
