# Generated by Django 5.2.6 on 2026-03-14 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_add_driver_cancel_reasons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20, verbose_name='Status')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Message At')),
                ('unread_count_rider', models.IntegerField(default=0, verbose_name='Unread Count (Rider)')),
                ('unread_count_driver', models.IntegerField(default=0, verbose_name='Unread Count (Driver)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(help_text='Driver assigned to the order', on_delete=django.db.models.deletion.CASCADE, related_name='driver_chats', to=settings.AUTH_USER_MODEL, verbose_name='Driver')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='order.order', verbose_name='Order')),
                ('rider', models.ForeignKey(help_text='Rider who created the order', on_delete=django.db.models.deletion.CASCADE, related_name='rider_chats', to=settings.AUTH_USER_MODEL, verbose_name='Rider')),
            ],
            options={
                'verbose_name': 'Order Chat',
                'verbose_name_plural': '13 Order Chats',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('rider', 'Rider'), ('driver', 'Driver')], max_length=10, verbose_name='Sender Type')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='order_chat/attachments/', verbose_name='Attachment')),
                ('file_type', models.CharField(blank=True, choices=[('image', 'Image'), ('file', 'File'), ('audio', 'Audio')], max_length=20, null=True, verbose_name='File Type')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='File Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='order.orderchat', verbose_name='Chat')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Order Chat Message',
                'verbose_name_plural': '14 Order Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='orderchat',
            index=models.Index(fields=['order'], name='order_chat_order_idx'),
        ),
        migrations.AddIndex(
            model_name='orderchat',
            index=models.Index(fields=['rider'], name='order_chat_rider_idx'),
        ),
        migrations.AddIndex(
            model_name='orderchat',
            index=models.Index(fields=['driver'], name='order_chat_driver_idx'),
        ),
        migrations.AddIndex(
            model_name='orderchat',
            index=models.Index(fields=['status'], name='order_chat_status_idx'),
        ),
        migrations.AddIndex(
            model_name='orderchatmessage',
            index=models.Index(fields=['chat'], name='order_chat_msg_chat_idx'),
        ),
        migrations.AddIndex(
            model_name='orderchatmessage',
            index=models.Index(fields=['sender'], name='order_chat_msg_sender_idx'),
        ),
        migrations.AddIndex(
            model_name='orderchatmessage',
            index=models.Index(fields=['created_at'], name='order_chat_msg_created_idx'),
        ),
    ]
