# Generated by Django 5.2.6 on 2026-03-22 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_add_rating_target_to_feedback_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingfeedbacktag',
            options={'ordering': ['rating_target', 'tag_type', 'name'], 'verbose_name': 'Rating Feedback Tag', 'verbose_name_plural': '11 Rating Feedback Tags'},
        ),
    ]
