# Generated by Django 5.2.6 on 2026-04-14 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_status_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrderPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatting_preference', models.CharField(choices=[('no_communication', 'No Communication'), ('casual', 'Casual'), ('friendly', 'Friendly')], default='no_communication', max_length=20)),
                ('temperature_preference', models.CharField(choices=[('warm', 'Warm (25°C and above)'), ('comfortable', 'Comfortable (22-24°C)'), ('cool', 'Cool (18-21°C)'), ('cold', 'Cold (below 18°C)')], default='comfortable', max_length=20)),
                ('music_preference', models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('hip_hop', 'Hip Hop'), ('electronic', 'Electronic'), ('country', 'Country'), ('no_music', 'No Music')], default='pop', max_length=20)),
                ('volume_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('mute', 'Mute')], default='medium', max_length=10)),
                ('pet_preference', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
                ('kids_chair_preference', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
                ('wheelchair_preference', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
                ('gender_preference', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=20)),
                ('favorite_driver_preference', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_preferences_template', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Order Preferences',
                'verbose_name_plural': '04b User Order Preferences',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user'], name='user_ord_pref_user_idx'), models.Index(fields=['updated_at'], name='user_ord_pref_updated_idx')],
            },
        ),
    ]
