# Generated by Django 5.2.6

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_userorderpreferences'),
        ('payment', '0001_saved_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='saved_card',
            field=models.ForeignKey(
                blank=True,
                help_text='Rider saved card used when payment_type is card.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='orders',
                to='payment.savedcard',
                verbose_name='Saved payment card',
            ),
        ),
    ]
