# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_saved_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_trip_payment_amount_cents',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name='Charged amount (cents)',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_trip_payment_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_trip_payment_error',
            field=models.TextField(
                blank=True,
                help_text='Last card charge error (e.g. if complete was blocked).',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_trip_payment_intent_id',
            field=models.CharField(
                blank=True,
                help_text='Set when card payment succeeds on trip complete.',
                max_length=255,
                verbose_name='Stripe PaymentIntent (trip)',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_trip_payment_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('not_applicable', 'Not applicable'),
                    ('succeeded', 'Succeeded'),
                ],
                default='not_applicable',
                max_length=32,
            ),
        ),
    ]
