# Generated by Django 5.2.6 on 2026-04-21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0019_orderitem_latlon_precision"),
        ("order", "0021_order_stripe_trip_payment"),
    ]

    operations = []

