# Generated by Django 5.2.6 on 2026-04-29 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_surgepricing_latlon_precision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverWalletBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_card', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available_hola_wallet_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lifetime_card', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lifetime_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lifetime_hola_wallet_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_balance', to=settings.AUTH_USER_MODEL, verbose_name='Driver')),
            ],
            options={
                'verbose_name': 'Driver Wallet Balance',
                'verbose_name_plural': '16 Driver Wallet Balances',
                'indexes': [models.Index(fields=['updated_at'], name='dr_wallet_updated_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('earning', 'Earning'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Adjustment')], max_length=20)),
                ('payment_type', models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('hola_wallet_cash', 'Hola Wallet Cash')], help_text='card|cash|hola_wallet_cash', max_length=30, verbose_name='Payment Type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for earnings, negative for withdrawals.', max_digits=12, verbose_name='Signed Amount')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='order.drivercashout', verbose_name='Cashout')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Driver')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Driver Wallet Transaction',
                'verbose_name_plural': '17 Driver Wallet Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver'], name='dr_wallet_tx_driver_idx'), models.Index(fields=['kind'], name='dr_wallet_tx_kind_idx'), models.Index(fields=['payment_type'], name='dr_wallet_tx_paytype_idx'), models.Index(fields=['created_at'], name='dr_wallet_tx_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('order', 'kind'), name='uniq_wallet_tx_order_kind'), models.UniqueConstraint(condition=models.Q(('cashout__isnull', False)), fields=('cashout', 'kind'), name='uniq_wallet_tx_cashout_kind')],
            },
        ),
    ]
