# Generated by Django 5.0.7 on 2026-06-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_driverwalletbalance_driverwallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='latitude_from',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=24, null=True, verbose_name='Latitude From'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='latitude_to',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=24, null=True, verbose_name='Latitude To'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='longitude_from',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=24, null=True, verbose_name='Longitude From'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='longitude_to',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=24, null=True, verbose_name='Longitude To'),
        ),
        migrations.AlterField(
            model_name='surgepricing',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=24, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='surgepricing',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=24, null=True, verbose_name='Longitude'),
        ),
    ]
