# Generated by Django 5.0.7 on 2026-07-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_ridetype_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ridetype',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Ride Type', 'verbose_name_plural': '02 Ride Types'},
        ),
    ]
