# Generated by Django 5.2.6 on 2026-04-15 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_role', models.CharField(choices=[('rider', 'Rider'), ('driver', 'Driver')], db_index=True, default='rider', help_text='Rider: pay for trips. Driver: optional cards (e.g. payouts) — product-specific.', max_length=20)),
                ('stripe_payment_method_id', models.CharField(help_text='Stripe PaymentMethod id (pm_…).', max_length=255, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe Customer id (cus_…) this PM is attached to.', max_length=255)),
                ('brand', models.CharField(blank=True, max_length=32)),
                ('last4', models.CharField(blank=True, max_length=4)),
                ('exp_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exp_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('funding', models.CharField(blank=True, help_text='Stripe card funding: credit, debit, prepaid, unknown.', max_length=20)),
                ('nickname', models.CharField(blank=True, help_text='Optional label shown in the app.', max_length=64)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='False when detached in Stripe or removed in app.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved card',
                'verbose_name_plural': 'Saved cards',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user', 'holder_role', 'is_active'], name='payment_sav_user_id_b1f420_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'holder_role'), name='savedcard_unique_default_per_user_holder_role')],
            },
        ),
    ]
