# Generated by Django 5.2.6 on 2025-11-22 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('rider', 'Rider'), ('driver', 'Driver')], help_text='Whether the user is a Rider or Driver', max_length=10, verbose_name='User Type')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending')], default='open', max_length=20, verbose_name='Status')),
                ('subject', models.CharField(blank=True, help_text='Subject or title of the conversation', max_length=255, null=True, verbose_name='Subject')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='Timestamp of the last message in this conversation', null=True, verbose_name='Last Message At')),
                ('unread_count_support', models.IntegerField(default=0, help_text='Number of unread messages for support', verbose_name='Unread Count (Support)')),
                ('unread_count_user', models.IntegerField(default=0, help_text='Number of unread messages for user', verbose_name='Unread Count (User)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(help_text='Rider or Driver who started the conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': '01 Conversations',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Message content', verbose_name='Message')),
                ('is_read_by_support', models.BooleanField(default=False, help_text='Whether support has read this message', verbose_name='Is Read By Support')),
                ('is_read_by_user', models.BooleanField(default=False, help_text='Whether user has read this message', verbose_name='Is Read By User')),
                ('is_from_support', models.BooleanField(default=False, help_text='Whether this message is from support team', verbose_name='Is From Support')),
                ('attachment', models.FileField(blank=True, help_text='File attachment (image, document, etc.)', null=True, upload_to='chat/attachments/', verbose_name='Attachment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='Conversation')),
                ('sender', models.ForeignKey(help_text='User who sent the message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': '02 Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user'], name='conversation_user_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status'], name='conversation_status_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='conversation_last_msg_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'status'], name='conversation_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation'], name='message_conversation_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='message_sender_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='message_created_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='message_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read_by_support', 'is_read_by_user'], name='message_read_idx'),
        ),
    ]
