# Generated by Django 5.2.6 on 2025-11-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, help_text='Original name of the uploaded file', max_length=255, null=True, verbose_name='File Name'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('file', 'File'), ('audio', 'Audio')], help_text='Type of file attachment', max_length=20, null=True, verbose_name='File Type'),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, help_text='File attachment (image, document, audio, etc.)', null=True, upload_to='chat/attachments/', verbose_name='Attachment'),
        ),
    ]
