# Generated by Django 5.0.7 on 2026-06-17 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_replace_with_chatroom_chatmessage'),
        ('order', '0025_latlon_precision_18'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_rooms_as_admin', to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
                ('orders', models.ManyToManyField(blank=True, related_name='support_rooms', to='order.order', verbose_name='Related orders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_rooms', to=settings.AUTH_USER_MODEL, verbose_name='User (Rider/Driver)')),
            ],
            options={
                'verbose_name': 'Support Room',
                'verbose_name_plural': '03 Support Rooms',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('system', 'System')], default='user', max_length=10)),
                ('message', models.TextField(blank=True, default='', verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to='order.order')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.supportroom', verbose_name='Support Room')),
            ],
            options={
                'verbose_name': 'Support Message',
                'verbose_name_plural': '04 Support Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportroom',
            index=models.Index(fields=['user'], name='supportroom_user_idx'),
        ),
        migrations.AddIndex(
            model_name='supportroom',
            index=models.Index(fields=['admin'], name='supportroom_admin_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportroom',
            constraint=models.UniqueConstraint(fields=('user', 'admin'), name='supportroom_unique_user_admin'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['room'], name='supportmsg_room_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['sender'], name='supportmsg_sender_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['created_at'], name='supportmsg_created_idx'),
        ),
    ]
